name: Build and test
on: push
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup protoc
      run: |
        # TODO: Download in the project
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - run: dotnet build rpc-csharp
    - run: dotnet test rpc-csharp-test